# Настройки статического анализа Dart:
# поиск ошибок, предупреждений и нарушений правил оформления.
#
# Результаты отображаются в средах разработки с поддержкой Dart:
# https://dart.dev/tools#ides-and-editors. Анализ также можно запустить
# из командной строки командой `flutter analyze`.

# Подключаем рекомендованные правила для приложений, пакетов
# и плагинов Flutter, поддерживающие принятые практики разработки.
analyzer:
  exclude:
    - build/**
    - android/**
include: package:flutter_lints/flutter.yaml

linter:
  # В следующем разделе можно настроить правила анализа:
  # отключить правила из подключённого `package:flutter_lints/flutter.yaml`
  # или включить дополнительные. Полный список правил
  # и документация доступны на https://dart.dev/lints.
  #
  # Вместо отключения правила для всего проекта можно
  # подавить его для отдельной строки кода
  # или файла Dart с помощью `// ignore: name_of_lint`
  # и `// ignore_for_file: name_of_lint` соответственно.
  # Директива располагается в строке или файле, где срабатывает правило.
  rules:
    # avoid_print: false  # Раскомментируйте для отключения правила `avoid_print`
    # prefer_single_quotes: true  # Раскомментируйте для включения `prefer_single_quotes`

# Дополнительная документация:
# https://dart.dev/guides/language/analysis-options
